name: morse_codec
description: A Morse code codec with full character support.
version: 1.0.0

issue_tracker: https://github.com/Gorniaky/dart_morse_codec/issues
repository: https://github.com/Gorniaky/dart_morse_codec

topics:
  - convert
  - morse

environment:
  sdk: ^3.11.5

dev_dependencies:
  args: ^2.7.0
  lints: ^6.0.0
  pub_semver: ^2.2.0
  test: ^1.25.6
